### ISSUE TITLE
Add monadic and combinators

### ISSUE THREAD

**Issue by gallais** [gallais/idris-tparsec#11]
I can't find good names for [these](https://github.com/gallais/agdarsec/commit/a84181ee0c7df0fcd1bc9fdd25629cc0f0026787#diff-e364d27e0984009373bf493d31f07f85R129) in Idris: the `m` is already taken by the `Maybe`-tainted
combinators.

**Comment by clayrat** [comment]
I was thinking to rename the existing ones to `..f` for "failure", what do you think?

**Comment by gallais** [comment]
I think of it as saying that one parser is `optional` rather than `failure`.
So maybe `opt`?

**Comment by clayrat** [comment]
Added in https://github.com/gallais/idris-tparsec/commit/1432b6243384c139f4d4be6601a64f081ac24b0d (renaming done in https://github.com/gallais/idris-tparsec/commit/dc306d6a8171ab94e3572d7014eab182afe4050f)

**Comment by gallais** [comment]
Perfect!
