### ISSUE TITLE
Add JSON parser

### ISSUE THREAD

**Issue by clayrat** [gallais/idris-tparsec#35]
It's so ubiquitous it probably makes sense to have an implementation out of the box.

**Comment by gallais** [comment]
What should the output format be? A `Map String String`? Or should we have a
more structured representation that allows user to specify sub-parsers?
In which case it would become a bit similar to gallais/agdARGS, I think.

**Comment by clayrat** [comment]
I guess the simplest way would be to re-use https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Language/JSON/Data.idr (although I'm not sure if that would carry over to Idris2).
