### ISSUE TITLE
Is DecEq necessary for tokens?

### ISSUE THREAD

**Issue by clayrat** [gallais/idris-tparsec#8]
As far I see, the `DecEq` constraint on tokens is only used in `Combinators.exact`, where it is immediately converted to a boolean. Seems like a weaker `Eq` constraint could be used here, sparing the user of writing things like counterproofs. Is this an artifact of an Agda port, or did you intend to have this constraint?

**Comment by gallais** [comment]
> Is this an artifact of an Agda port, or did you intend to have this constraint?

It's more of a semantical statement about what `exact` is doing. I wouldn't
be opposed to changing the constraint as the extra information is indeed not
being used.
